# Generated by Django 3.2.4 on 2021-09-29 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('name', models.CharField(max_length=120)),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('passwd', models.CharField(max_length=100)),
                ('ppic', models.ImageField(default='', upload_to='static/pro+file/')),
                ('address', models.TextField(max_length=2000)),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='cpic',
            field=models.ImageField(default='', upload_to='static/category/'),
        ),
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=200)),
                ('headlines', models.CharField(max_length=400)),
                ('subject', models.CharField(max_length=800)),
                ('newsdes', models.TextField(max_length=8000)),
                ('newspic', models.ImageField(default='', upload_to='static/profile/')),
                ('ndate', models.DateField()),
                ('ncategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.category')),
            ],
        ),
    ]
