# Generated by Django 3.2.4 on 2021-10-04 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20211002_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='npic',
            field=models.ImageField(default='', upload_to='static/notification/'),
        ),
    ]
